kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
spec:
  resources:
    requests:
      storage: 16Gi
  accessModes:
    - "ReadWriteMany"
  storageClassName: standard
  selector:
    matchLabels:
      volume: my-volume
