# https://github.com/kubernetes/kubernetes/tree/master/examples/volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-disk-1
  annotations:
    volume.beta.kubernetes.io/mount-options: "discard"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: ext4
    pdName: gce-disk-1
