# https://kubernetes.io/docs/resources-reference/v1.7/#gcepersistentdiskvolumesource-v1-core
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: my-volume
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - "ReadWriteMany"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "database"
  storageClassName: standard
