apiVersion: v1
kind: Pod
metadata:
  labels:
    name: influxdb
  name: influxdb
spec:
  volumes:
    - name: "influxdb-data"
      hostPath:
        path: "/var/lib/influxdb"
        # "/var/lib/influxdb"
  containers:
    - image: index.docker.io/influxdb/influxdb:latest
      # index.docker.io/DOCKER_USER/influxdb:latest
      # index.docker.io/edorsett/influxdb:latest
      name: influxdb
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "500m"
          memory: "128Mi"
      volumeMounts:
        - mountPath: "/influxdb"
        # ".influxdb"
          name: "influxdb-data"
      livenessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 15
        timeoutSeconds: 1
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
  imagePullSecrets:
    - name: myregistrykey
