apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer2
    chapter: jobs
  name: consumers2
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer2
        chapter: jobs
    spec:
      containers:
      - name: worker
        image: "gcr.io/kuar-demo/kuard-amd64:1"
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-memq-server=http://broker:8080/memq/server"
        - "--keygen-memq-queue=keygen2"
      restartPolicy: OnFailure
