apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: message-queue
    component: broker
    chapter: jobs
  name: broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-queue
        component: broker
        chapter: jobs
    spec:
      containers:
      - name: broker
        image: "gcr.io/kuar-demo/kuard-amd64:1"
        imagePullPolicy: Always
