apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-queue
    component: broker
    chapter: jobs
  name: broker
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: message-queue
    component: broker
